# Generated by Django 4.1.4 on 2022-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eser_adi', models.CharField(max_length=127)),
                ('bestekar', models.CharField(max_length=127)),
                ('yuzyil', models.IntegerField()),
                ('gufte_yazari', models.CharField(max_length=127)),
                ('gufte_vezin', models.CharField(max_length=127)),
                ('gufte_nazim_bicim', models.CharField(max_length=127)),
                ('gufte_nazim_tur', models.CharField(max_length=127)),
                ('makam', models.JSONField()),
                ('usul', models.JSONField()),
                ('form', models.CharField(max_length=127)),
                ('subcomponents', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Usul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
    ]
