# Generated by Django 4.1.4 on 2023-01-06 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='makam_app.piece')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
